### ISSUE TITLE
Not an Issue, But a Compliment, Comment, and Question

### ISSUE THREAD

**Issue by vermont42** [andresinaka/Transformer#10]
Very clever! Reminds me of PaintCode. 

Here is how I solve this problem. Basically, I interpret special characters like ^ as formatting, similar to Markdown. The code is in the infoString property. 

https://github.com/vermont42/Conjugar/blob/master/Conjugar/StringExtensions.swift

On a related note, I am curious whether you use the same vos conjugations as the Real Academia Española. I used their conjugations in my app, but Wikipedia’s voseo article says that vos conjugations vary by country.

**Comment by andresinaka** [comment]
> Very clever! Reminds me of PaintCode.

Hey @vermont42! thanks for the compliment! I didn't know PaintCode, looks so cool and interesting!

> Here is how I solve this problem. Basically, I interpret special characters like ^ as formatting, similar to Markdown. The code is in the infoString property.
>
> https://github.com/vermont42/Conjugar/blob/master/Conjugar/StringExtensions.swift

You got an interesting and smart way of solving your problem! I liked it!

> On a related note, I am curious whether you use the same vos conjugations as the Real Academia Española. I used their conjugations in my app, but Wikipedia’s voseo article says that vos conjugations vary by country.

We use it as "Vos tenes" instead of "Tu tienes". I just googled a bit and found this article from the BBC explaining where the voseo comes from: http://www.bbc.com/mundo/noticias-america-latina-36928497

And also I found this a table from RAE in this article (http://www.bbc.com/mundo/noticias-america-latina-36928497) explains by country how is used. Search for "FORMAS DEL VOSEO VERBAL POR PAÍSES". I think Argentina is the country that uses the "vos" the most, actually I think I never heard any other latin americans use vos but in some regions of colombia... but of course sadly I haven't been to every region or area in south america to be able to make that an statement...

Hope I helped with that!

Best!
